### ISSUE TITLE
Language Support?

### ISSUE THREAD

**Issue by sayam93** [chatziko/ha-google-cloud-stt#10]
I have google_cloud_stt configured as my speech to text agent in Home Assistant's Voice Assistant. However, there are no other languages available (like Hindi) besides different variations of English. I have tried using both command_and_search and latest_short models both of which support a ton of languages besides English and its variants. Is this a limitation of Home Assistant or the custom integration?

**Comment by chatziko** [comment]
You first need to select "Hindi" in the "configuration" box, and then it will appear in the other boxes, see below:


![image](https://github.com/chatziko/ha-google-cloud-stt/assets/362089/474c6fe9-92a6-4914-b621-a665d509d0de)
