### ISSUE TITLE
Error: stt-stream-failed - Unexpected error during speech-to-text wit ATOM Echo

### ISSUE THREAD

**Issue by brostudiodev** [chatziko/ha-google-cloud-stt#13]
Did anyone encounter this issue?  Home Assistant v2024.6.2 and Atom Echo:
[10:03:23][D][voice_assistant:502]: State changed from STOPPING_MICROPHONE to AWAITING_RESPONSE
[10:03:23][D][voice_assistant:625]: Event Type: 0
[10:03:23][E][voice_assistant:755]: **Error: stt-stream-failed - Unexpected error during speech-to-text**
[10:03:23][D][voice_assistant:618]: Signaling stop...

I have configured STT plugin (via hacs + configuration.yaml:
stt:
  - platform: google_cloud_stt
    key_file: googlecloud.json
    model: command_and_search

and followed Google Cloud tts/sst guide. The googlecloud.json is send to config folder where configuration.json is visible. I can select google_cloud_stt in Assist's Speech to text so from HA perspective I am good to go.
Whenever I try to speak the voice is automatically shut down and error comes:
Error: stt-stream-failed - Unexpected error during speech-to-text

I tried with Piper and it is working (of course it is not accurate with my local language and works 5-6 seconds until output)

**Comment by brostudiodev** [comment]
I have found my issue. When I was creating Google project, the "Cloud Speech-to-Text API" was not enabled during my first try,,, HA tutorials and https://cloud.google.com/speech-to-text/docs/before-you-begin helped. Maybe this will be handy to someone who find similar issues

**Comment by nerijus** [comment]
Please close this issue then.

**Comment by brostudiodev** [comment]
Closed. Thanks for great HA plugin :)
