### ISSUE TITLE
The stt integration does not support any configuration parameters

### ISSUE THREAD

**Issue by felipecrs** [chatziko/ha-google-cloud-stt#3]
I'm receiving this error in my HA logs. Maybe some HA breaking change? I'm currently running with 2023.7.1.

```
Logger: homeassistant.helpers.config_validation
Source: helpers/config_validation.py:1065
First occurred: 9 de julho de 2023 às 13:01:36 (1 occurrences)
Last logged: 9 de julho de 2023 às 13:01:36

The stt integration does not support any configuration parameters, got [{'platform': 'google_cloud_stt', 'key_file': 'google-cloud-service-account.json', 'model': 'latest_short'}]. Please remove the configuration parameters from your configuration.
```

**Comment by chatziko** [comment]
I get the same after 2023.7, I gave it a quick look but couldn't find the issue.

However, despite the message in the logs the integration still works for me. Is it working for you?

**Comment by felipecrs** [comment]
Yes, it's working. Maybe it's a "bug" in HA?

**Comment by chatziko** [comment]
This is the culprit: https://github.com/home-assistant/core/pull/93954
Context: https://github.com/home-assistant/core/pull/93587/files

They seem to explicitly configure that `stt` has no configuration parameters, however `stt` allows to setup platforms (which is what ha-google-cloud-stt  does), so it should accept parameters.

**Comment by PulsarFX** [comment]
reported here: https://github.com/home-assistant/core/issues/97161

**Comment by PulsarFX** [comment]
Got an answer on this issue.
https://github.com/home-assistant/core/issues/97161#issuecomment-1841075614

**Comment by maslyankov** [comment]
I cannot setup the integration. It seems to maybe only work if you've setup the integration before this breaking change of HA. In my understanding, for this integration to be working it should support setup via UI.

**Comment by lordrak007** [comment]
Same issue, setup like described but te tts option in Voice Assistant does not occure.

**Comment by nerijus** [comment]
After setup I restarted HA and got 
The following integrations and platforms could not be set up:
    google_cloud_stt.stt (Show logs)
Log:
```
Logger: homeassistant.setup
Source: setup.py:481
First occurred: 17:00:15 (1 occurrences)
Last logged: 17:00:15
Unable to prepare setup for platform 'google_cloud_stt.stt': Platform not found (cannot import name 'speech' from 'google.cloud' (unknown location)).
```

Edit: it works after 2nd HA restart. So no, integration may not support setup via UI, it is working with current HA.
