### ISSUE TITLE
[enhancement] Allow phraseSets and customClasses

### ISSUE THREAD

**Issue by joie96** [chatziko/ha-google-cloud-stt#7]
Hey,

would it be possible to allow phraseSets and customClasses? This would improve the accuracy of speech recognition.
Maby we could specify this in configuration.yaml.

Here is an example: [https://cloud.google.com/speech-to-text/docs/adaptation?hl=en](https://cloud.google.com/speech-to-text/docs/adaptation?hl=en)

And for more info, see: [https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig#SpeechAdaptation](https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig#SpeechAdaptation)

Thanks for reading!

**Comment by chatziko** [comment]
This sounds cool, but I doubt I'll have time to implement it in the near future (especially given that it's not available in my native language :smile: )

**Comment by joie96** [comment]
Ah I see. :D 
Thank you anyway!
